name: teste-inicial
on:
    workflow_dispatch:
    push:
jobs:
    teste-inicial:
        runs-on: ubuntu-latest
        steps:
          - name: sha 1
            run: echo "Commit sha is $GITHUB_SHA"
          - name: sha 2
            run: echo "Commit sha is ${{ github.sha }}"